#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

# boot the app and any other necessary processes.
echo "This is where you might invoke a specific instance of a server for your app."
